### ISSUE TITLE
Issue: Side Pane doesn't work in Vivaldi browser

### ISSUE THREAD

**Issue by inovek** [belaviyo/edit-as-html#2]
The side pane in the Elements panel with the title "Sublime Text" and the button "Edit as HTML" appears in chrome. But doesn't appeared in [Vivaldis](vivaldi.net/) developer-tools.

The main extension button itself works like a charm in both browsers. But I'm interested also in the button for the developer-tools.

Could you look into that?

**Comment by belaviyo** [comment]
Seems like Vivaldi does not yet support "devtools_page" in the manifest. There is no way to fix this on my side!
https://github.com/belaviyo/edit-as-html/blob/master/sublime/manifest.json#L30
