### ISSUE TITLE
Issue Input event on Update

### ISSUE THREAD

**Issue by jclds139** [belaviyo/edit-as-html#9]
Many websites trigger updates from an "input" event. In my case I use Tiddlywiki for my notebooks and it doesn't autosave or update the preview without an input event, so even after updating the textarea content data still gets lost easily. Can this issue an "input" event to the textarea when updating the content as well?

**Comment by belaviyo** [comment]
Thanks for the report. As of the next release, both "Edit with Sublime Text" and "Edit with Notepad++" will issue `change` and `input` events on value updates.
